language: android
jdk:
  - oraclejdk8
android:
    components:
        - tools
        - platform-tools
        - build-tools-24.0.0
        - android-23
        - extra-android-m2repository
        - extra-android-support
before_install:
    - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
    - export JAVA_HOME=$JAVA8_HOME
script:
  - ./gradle build jacocoTestReport