language: android
jdk:
  - oraclejdk8
android:
    components:
        - tools
        - platform-tools
        - build-tools-24.0.0
        - android-23
        - extra-android-m2repository
        - extra-android-support
before_install:
    - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
    - export JAVA_HOME=$JAVA8_HOME
    - chmod +x gradlew
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
script:
  - ./gradlew build jacocoTestReport
after_success:
    - bash <(curl -s https://codecov.io/bash)